#!/usr/bin/env python3
"""
Generador del perfil de GitHub de Nikorasu-Vanetti.

Lee los repositorios vía la API de GitHub y regenera, a partir de datos reales:
  - assets/header.svg        Banner PCB/blueprint animado (identidad).
  - assets/languages.svg     Distribucion de lenguajes (barra + leyenda) animada.
  - assets/stats.svg         Tarjetas de metricas (repos, estrellas, lenguajes...).
  - Seccion PROJECTS del README.md (entre marcadores).

Sin dependencias externas: solo la libreria estandar.
Token: variable de entorno METRICS_TOKEN (preferida) o GITHUB_TOKEN.
"""

import json
import os
import re
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone

USERNAME = "Nikorasu-Vanetti"
API = "https://api.github.com"
ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets")
README = os.path.join(os.path.dirname(os.path.abspath(__file__)), "README.md")

# Identidad (lo unico curado a mano; el resto es 100% derivado de datos).
FULL_NAME = "Jose Nicolas Sanchez Zorrilla"
ALIAS = "NIKO . VANETTI"

# Textos por idioma. La identidad (nombre/alias) no se traduce; todo lo demas si.
LANGS = ["es", "en"]  # primero el default (es = README.md)
STRINGS = {
    "en": {
        "role": "Software Engineer  //  Developer tools, AI agents & embedded systems",
        "roles": [
            "Software Engineer  //  developer tools & IDEs",
            "AI agents & automation  //  Python, orchestration",
            "Embedded & mechatronics  //  C, C++, Verilog, FPGAs",
        ],
        "h_connect": "Connect",
        "h_stats": "GitHub stats & streak",
        "h_activity": "Contribution activity",
        "h_tech": "Tech stack",
        "h_trophies": "Trophies",
        "h_snake": "Contribution graph",
        "lang_title": "LANGUAGE DISTRIBUTION",
        "lang_note": "// computed from all owned repos",
        "stats": ["Repositories", "Total stars", "Languages", "Since"],
        "selected": "Selected work",
        "th": ["Project", "Stack", "What it is", "Status"],
        "private": "private", "public": "public", "stars": "stars",
        "about_title": "About",
        "about": (
            "I build developer tooling, AI agents and embedded/mechatronics systems. "
            "Most of my time goes to designing IDEs and automation that make hard things "
            "feel simple, working across the stack from the browser down to the silicon."),
        "bullets": [
            "Web & tooling: TypeScript, JavaScript, custom IDE/editor surfaces",
            "Systems & embedded: C, C++, Verilog (Tang Primer FPGAs), mechatronics at ITLA",
            "AI & automation: Python agents, workflow orchestration",
            "Mobile: Swift, Kotlin / Java",
        ],
        "generated": (
            "Everything on this profile is generated by code. The header, the metrics, the "
            "language chart and the project list are rendered from live repository data by "
            "[`generate.py`](./generate.py) and refreshed automatically by a GitHub Action. "
            "Nothing here is updated by hand."),
        "updated": "Last refreshed",
        "btn": "English",
    },
    "es": {
        "role": "Ingeniero de Software  //  Herramientas para devs, agentes IA y sistemas embebidos",
        "roles": [
            "Ingeniero de Software  //  herramientas para devs e IDEs",
            "Agentes IA y automatización  //  Python, orquestación",
            "Embebidos y mecatrónica  //  C, C++, Verilog, FPGAs",
        ],
        "h_connect": "Contacto",
        "h_stats": "Estadísticas y racha",
        "h_activity": "Actividad de contribuciones",
        "h_tech": "Tecnologías",
        "h_trophies": "Trofeos",
        "h_snake": "Gráfico de contribuciones",
        "lang_title": "DISTRIBUCIÓN DE LENGUAJES",
        "lang_note": "// calculado desde todos mis repos",
        "stats": ["Repositorios", "Estrellas", "Lenguajes", "Desde"],
        "selected": "Trabajo seleccionado",
        "th": ["Proyecto", "Stack", "Qué es", "Estado"],
        "private": "privado", "public": "público", "stars": "estrellas",
        "about_title": "Acerca de",
        "about": (
            "Construyo herramientas para desarrolladores, agentes de IA y sistemas "
            "embebidos/mecatrónicos. Dedico la mayor parte del tiempo a diseñar IDEs y "
            "automatizaciones que vuelven simple lo difícil, trabajando en todo el stack "
            "desde el navegador hasta el silicio."),
        "bullets": [
            "Web y tooling: TypeScript, JavaScript, editores/IDE a medida",
            "Sistemas y embebidos: C, C++, Verilog (FPGAs Tang Primer), mecatrónica en el ITLA",
            "IA y automatización: agentes en Python, orquestación de flujos",
            "Móvil: Swift, Kotlin / Java",
        ],
        "generated": (
            "Todo este perfil está generado por código. La cabecera, las métricas, el gráfico "
            "de lenguajes y la lista de proyectos se renderizan con datos reales de los repos "
            "mediante [`generate.py`](./generate.py) y se refrescan solos con una GitHub Action. "
            "Nada aquí se edita a mano."),
        "updated": "Última actualización",
        "btn": "Español",
    },
}
FILES = {"es": "README.md", "en": "README.en.md"}  # español por defecto

# Colores oficiales de GitHub Linguist (los que falten caen a un gris).
LINGUIST = {
    "TypeScript": "#3178c6", "JavaScript": "#f1e05a", "Python": "#3572A5",
    "C": "#555555", "C++": "#f34b7d", "HTML": "#e34c26", "CSS": "#563d7c",
    "Swift": "#F05138", "Java": "#b07219", "Kotlin": "#A97BFF",
    "Verilog": "#848bf3", "Ruby": "#701516", "Batchfile": "#C1F12E",
    "Shell": "#89e051", "Go": "#00ADD8", "Rust": "#dea584", "Dart": "#00B4AB",
    "Vue": "#41b883", "PHP": "#4F5D95", "C#": "#178600",
}
DEFAULT_COLOR = "#6b7280"


# --------------------------------------------------------------------------- #
#  Capa de datos                                                              #
# --------------------------------------------------------------------------- #
def token():
    tk = os.environ.get("METRICS_TOKEN") or os.environ.get("GITHUB_TOKEN") or ""
    return tk.strip().lstrip("﻿")  # tolera BOM/espacios de un secret mal codificado


def api_get(path):
    url = path if path.startswith("http") else API + path
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", USERNAME + "-profile-generator")
    tk = token()
    if tk:
        req.add_header("Authorization", "Bearer " + tk)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def fetch_repos():
    """Repos propios (publicos + privados si el token lo permite), sin forks."""
    repos = []
    # Con token de usuario: /user/repos ve privados. Si falla, fallback publico.
    endpoints = [
        "/user/repos?affiliation=owner&per_page=100&sort=updated",
        "/users/" + USERNAME + "/repos?per_page=100&sort=updated",
    ]
    for ep in endpoints:
        try:
            data = api_get(ep)
            if isinstance(data, list) and data:
                repos = data
                break
        except urllib.error.HTTPError:
            continue
    out = []
    for r in repos:
        if r.get("fork"):
            continue
        if r.get("name", "").lower() == USERNAME.lower():
            continue  # el propio repo de perfil
        out.append(r)
    return out


def fetch_languages(repo):
    try:
        return api_get("/repos/" + USERNAME + "/" + repo["name"] + "/languages")
    except Exception:
        return {}


def fetch_profile():
    try:
        return api_get("/users/" + USERNAME)
    except Exception:
        return {}


def aggregate_languages(repos):
    totals = {}
    for r in repos:
        for lang, b in fetch_languages(r).items():
            totals[lang] = totals.get(lang, 0) + b
    grand = sum(totals.values()) or 1
    rows = []
    for lang, b in sorted(totals.items(), key=lambda kv: kv[1], reverse=True):
        rows.append({
            "name": lang,
            "bytes": b,
            "pct": round(b / grand * 100, 1),
            "color": LINGUIST.get(lang, DEFAULT_COLOR),
        })
    return rows


# --------------------------------------------------------------------------- #
#  Utilidades                                                                  #
# --------------------------------------------------------------------------- #
def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def write(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("wrote", os.path.relpath(path))


# --------------------------------------------------------------------------- #
#  SVG: cabecera PCB animada                                                   #
# --------------------------------------------------------------------------- #
def header_svg(top_lang, roles):
    """Cabecera neon multicolor: circuito animado + nombre con gradiente que fluye
    + roles rotativos. `roles` es una lista de frases que se alternan."""
    W, H = 1000, 340
    silk = "#eaf2ff"
    # Paleta neon repartida por los trazos del circuito.
    NEON = ["#22d3ee", "#a855f7", "#f472b6", "#34d399",
            "#fbbf24", "#60a5fa", "#fb7185", "#a3e635"]

    # Trazos PCB que enmarcan el texto (arriba, abajo y zona del chip a la derecha).
    traces = [
        "M0,40 L150,40 L185,75 L360,75", "M0,86 L110,86 L150,46 L250,46",
        "M0,300 L140,300 L180,260 L380,260", "M0,256 L90,256 L130,296 L300,296",
        "M1000,52 L840,52 L800,92 L660,92", "M1000,300 L860,300 L820,260 L640,260",
        "M1000,150 L900,150 L865,185 L760,185", "M1000,210 L915,210 L880,175 L800,175",
        "M520,340 L520,300 L490,270 L490,232", "M610,340 L610,304 L642,272 L642,236",
        "M150,40 L150,8", "M380,260 L380,332",
    ]
    vias = [(150, 40), (360, 75), (250, 46), (140, 300), (380, 260), (300, 296),
            (840, 52), (660, 92), (860, 300), (640, 260), (900, 150), (760, 185),
            (490, 232), (642, 236), (915, 210)]

    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
             f'width="{W}" height="{H}" role="img" '
             f'aria-label="{esc(FULL_NAME)} - {esc(roles[0]) if roles else ""}">']

    # ---- defs ----
    parts.append('<defs>')
    parts.append('<radialGradient id="bg" cx="50%" cy="38%" r="85%">'
                 '<stop offset="0%" stop-color="#161a40"/>'
                 '<stop offset="45%" stop-color="#0b1230"/>'
                 '<stop offset="100%" stop-color="#05030f"/></radialGradient>')
    # gradiente que fluye por el nombre (repeat + translate = loop sin costuras)
    parts.append('<linearGradient id="ng" gradientUnits="userSpaceOnUse" '
                 'x1="60" y1="0" x2="380" y2="0" spreadMethod="repeat">'
                 '<stop offset="0" stop-color="#22d3ee"/><stop offset="0.17" stop-color="#60a5fa"/>'
                 '<stop offset="0.34" stop-color="#a855f7"/><stop offset="0.5" stop-color="#f472b6"/>'
                 '<stop offset="0.67" stop-color="#fb7185"/><stop offset="0.84" stop-color="#fbbf24"/>'
                 '<stop offset="1" stop-color="#22d3ee"/>'
                 '<animateTransform attributeName="gradientTransform" type="translate" '
                 'values="0 0; 320 0" dur="7s" repeatCount="indefinite"/></linearGradient>')
    parts.append('<linearGradient id="pins" x1="0" y1="0" x2="1" y2="1">'
                 '<stop offset="0" stop-color="#22d3ee"/><stop offset="0.5" stop-color="#a855f7"/>'
                 '<stop offset="1" stop-color="#f472b6"/></linearGradient>')
    parts.append('<filter id="glow" x="-60%" y="-60%" width="220%" height="220%">'
                 '<feGaussianBlur stdDeviation="3" result="b"/>'
                 '<feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>')
    parts.append('<filter id="soft"><feGaussianBlur stdDeviation="26"/></filter>')
    parts.append('<pattern id="grid" width="34" height="34" patternUnits="userSpaceOnUse">'
                 '<path d="M34 0H0V34" fill="none" stroke="#1b2350" stroke-width="1"/></pattern>')
    # velo oscuro a la izquierda: garantiza contraste del texto sobre la aurora
    parts.append('<linearGradient id="scrim" x1="0" y1="0" x2="1" y2="0">'
                 '<stop offset="0" stop-color="#05030f" stop-opacity="0.86"/>'
                 '<stop offset="0.42" stop-color="#05030f" stop-opacity="0.6"/>'
                 '<stop offset="0.72" stop-color="#05030f" stop-opacity="0"/></linearGradient>')
    parts.append('</defs>')

    parts.append("""<style>
      .draw{stroke-dasharray:1400;stroke-dashoffset:1400;animation:draw 2.4s ease forwards;}
      .flow{stroke-dasharray:5 26;animation:flow 1.5s linear infinite;}
      @keyframes draw{to{stroke-dashoffset:0;}}
      @keyframes flow{to{stroke-dashoffset:-310;}}
      .via{animation:pulse 2.6s ease-in-out infinite;transform-origin:center;}
      @keyframes pulse{0%,100%{opacity:.5;r:3;}50%{opacity:1;r:5.5;}}
      .led{animation:blink 1.5s steps(1) infinite;}
      @keyframes blink{0%,55%{opacity:1;}56%,100%{opacity:.2;}}
      .pin{animation:sweep 2.4s ease-in-out infinite;}
      @keyframes sweep{0%,100%{opacity:.3;}50%{opacity:1;}}
      .aur{animation:drift 9s ease-in-out infinite;}
      @keyframes drift{0%,100%{transform:translate(0,0);}50%{transform:translate(40px,18px);}}
      .aur2{animation:drift2 11s ease-in-out infinite;}
      @keyframes drift2{0%,100%{transform:translate(0,0);}50%{transform:translate(-46px,-14px);}}
      .fade{opacity:0;animation:fade 1s ease .2s forwards;}
      .fade2{opacity:0;animation:fade 1s ease .7s forwards;}
      @keyframes fade{to{opacity:1;}}
      .name{opacity:0;animation:fade 1s ease .2s forwards, shine 3s ease-in-out 1.4s infinite;}
      @keyframes shine{0%,100%{filter:drop-shadow(0 0 6px rgba(96,165,250,.5));}50%{filter:drop-shadow(0 0 16px rgba(244,114,182,.7));}}
      .role{opacity:0;animation:role 9s ease-in-out infinite;}
      @keyframes role{0%{opacity:0;transform:translateY(6px);}3%{opacity:1;transform:translateY(0);}28%{opacity:1;}33%,100%{opacity:0;}}
      .cur{animation:cur 1s steps(1) infinite;}
      @keyframes cur{0%,49%{opacity:1;}50%,100%{opacity:0;}}
      text{font-family:'Segoe UI',Helvetica,Arial,sans-serif;}
      .mono{font-family:'Cascadia Code','Consolas',ui-monospace,monospace;}
    </style>""")

    # ---- fondo + aurora + grid ----
    parts.append(f'<rect width="{W}" height="{H}" rx="18" fill="url(#bg)"/>')
    parts.append('<g filter="url(#soft)">')
    parts.append('<circle class="aur" cx="150" cy="70" r="120" fill="#3b1f8f" opacity="0.30"/>')
    parts.append('<circle class="aur2" cx="820" cy="240" r="150" fill="#0e5a6b" opacity="0.34"/>')
    parts.append('<circle class="aur" cx="640" cy="40" r="110" fill="#8a1f5c" opacity="0.22"/>')
    parts.append('</g>')
    parts.append(f'<rect width="{W}" height="{H}" rx="18" fill="url(#grid)" opacity="0.5"/>')
    parts.append(f'<rect x="3" y="3" width="{W - 6}" height="{H - 6}" rx="16" fill="none" '
                 f'stroke="#3a4790" stroke-width="1.5" opacity="0.6"/>')

    # ---- circuito (base que se dibuja + corriente que fluye), color por trazo ----
    for i, d in enumerate(traces):
        c = NEON[i % len(NEON)]
        parts.append(f'<path d="{d}" fill="none" stroke="{c}" stroke-width="2.4" opacity="0.5" '
                     f'stroke-linecap="round" stroke-linejoin="round" class="draw" '
                     f'style="animation-delay:{i * 0.08:.2f}s"/>')
        parts.append(f'<path d="{d}" fill="none" stroke="{c}" stroke-width="2.4" '
                     f'stroke-linecap="round" filter="url(#glow)" class="flow" '
                     f'style="animation-delay:{i * 0.12:.2f}s"/>')
    for i, (x, y) in enumerate(vias):
        c = NEON[i % len(NEON)]
        parts.append(f'<circle cx="{x}" cy="{y}" r="3" fill="{c}" class="via" '
                     f'filter="url(#glow)" style="animation-delay:{i * 0.13:.2f}s"/>')

    # ---- chip / IC ----
    cx, cy, cw, ch = 770, 86, 150, 96
    parts.append('<g class="fade2">')
    parts.append(f'<rect x="{cx}" y="{cy}" width="{cw}" height="{ch}" rx="10" fill="#0c1338" '
                 f'stroke="url(#pins)" stroke-width="2"/>')
    for i in range(6):
        py = cy + 14 + i * 13
        c1, c2 = NEON[i % len(NEON)], NEON[(i + 3) % len(NEON)]
        parts.append(f'<rect x="{cx - 10}" y="{py}" width="10" height="6" rx="2" fill="{c1}" '
                     f'class="pin" filter="url(#glow)" style="animation-delay:{i * 0.16:.2f}s"/>')
        parts.append(f'<rect x="{cx + cw}" y="{py}" width="10" height="6" rx="2" fill="{c2}" '
                     f'class="pin" filter="url(#glow)" style="animation-delay:{i * 0.16 + 0.3:.2f}s"/>')
    parts.append(f'<circle cx="{cx + 18}" cy="{cy + 18}" r="5" fill="none" stroke="#22d3ee" '
                 f'stroke-width="1.5"/>')
    parts.append(f'<text x="{cx + 36}" y="{cy + 24}" fill="{silk}" class="mono" font-size="13" '
                 f'letter-spacing="1">JNSZ-01</text>')
    parts.append(f'<text x="{cx + 18}" y="{cy + 66}" fill="#22d3ee" class="mono" font-size="10" '
                 f'opacity="0.8">core: {esc(top_lang)}</text>')
    parts.append('</g>')

    # ---- velo para legibilidad del texto ----
    parts.append(f'<rect x="0" y="0" width="{W}" height="{H}" rx="18" fill="url(#scrim)"/>')

    # ---- pill de estado (ancho calculado para que el texto no se salga) ----
    pill_txt = "available . open to work"
    pill_w = 44 + int(len(pill_txt) * 7.3)
    parts.append('<g class="fade">')
    parts.append(f'<rect x="56" y="40" width="{pill_w}" height="30" rx="15" fill="#0d1640" '
                 f'stroke="#2dd4bf" stroke-width="1.2"/>')
    parts.append('<circle cx="76" cy="55" r="5" fill="#34d399" class="led" filter="url(#glow)"/>')
    parts.append(f'<text x="92" y="59" fill="{silk}" class="mono" font-size="12" '
                 f'letter-spacing="0.5">{esc(pill_txt)}</text>')
    parts.append('</g>')

    # ---- nombre con gradiente animado ----
    parts.append(f'<text x="58" y="156" font-size="38" font-weight="800" letter-spacing="0.5" '
                 f'fill="url(#ng)" class="name">{esc(FULL_NAME)}</text>')
    parts.append(f'<text x="60" y="198" fill="#f0abfc" class="mono fade2" font-size="20" '
                 f'font-weight="700" letter-spacing="4" filter="url(#glow)">aka {esc(ALIAS)}</text>')

    # ---- roles rotativos + cursor ----
    parts.append('<g class="fade2">')
    for i, ph in enumerate(roles[:3]):
        parts.append(f'<text x="60" y="244" fill="#9fb3d8" class="mono role" font-size="15" '
                     f'style="animation-delay:{i * 3:.0f}s">&gt; {esc(ph)}'
                     f'<tspan class="cur" fill="#fbbf24">_</tspan></text>')
    parts.append('</g>')

    # ---- stack chips (mini etiquetas de colores) ----
    chips = [("TypeScript", "#3178c6"), ("Python", "#3572A5"), ("C / C++", "#f34b7d"),
             ("Verilog", "#848bf3")]
    xx = 60
    parts.append('<g class="fade2">')
    for label, c in chips:
        bw = 38 + int(len(label) * 7.3)  # cabe dot + texto mono 12 + padding
        parts.append(f'<rect x="{xx}" y="276" width="{bw}" height="26" rx="13" fill="#0d1640" '
                     f'stroke="{c}" stroke-width="1.3"/>')
        parts.append(f'<circle cx="{xx + 14}" cy="289" r="4" fill="{c}"/>')
        parts.append(f'<text x="{xx + 26}" y="293" fill="{silk}" class="mono" font-size="12">'
                     f'{esc(label)}</text>')
        xx += bw + 12
    parts.append('</g>')

    parts.append('</svg>')
    return "".join(parts)


# --------------------------------------------------------------------------- #
#  SVG: distribucion de lenguajes                                             #
# --------------------------------------------------------------------------- #
def languages_svg(rows, title, note):
    rows = rows[:8]
    W = 1000
    pad = 28
    barx, barw, bary, barh = pad, W - 2 * pad, 88, 26
    legcols = 4
    legrows = (len(rows) + legcols - 1) // legcols
    H = bary + barh + 56 + legrows * 30

    parts = []
    parts.append(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
                 f'width="{W}" height="{H}" role="img" aria-label="Language distribution">')
    css = """
    <style>
      @keyframes grow{from{width:0;}}
      @keyframes fin{from{opacity:0;transform:translateY(6px);}to{opacity:1;transform:translateY(0);}}
      .seg{animation:grow 1.4s cubic-bezier(.2,.7,.2,1) forwards;}
      .lg{opacity:0;animation:fin .6s ease forwards;}
      .via{animation:vp 2.6s ease-in-out infinite;transform-origin:center;}
      @keyframes vp{0%,100%{opacity:.4;}50%{opacity:1;}}
      text{font-family:'Cascadia Code','Consolas',ui-monospace,monospace;}
    </style>
    """
    parts.append(css)
    parts.append(f'<rect width="{W}" height="{H}" rx="16" fill="#071524"/>')
    parts.append(f'<rect x="2" y="2" width="{W - 4}" height="{H - 4}" rx="15" fill="none" '
                 f'stroke="#0e2a45" stroke-width="1.5"/>')
    # vias decorativas en esquinas
    for (vx, vy, dly) in [(18, 18, 0), (W - 18, 18, .6), (18, H - 18, 1.2), (W - 18, H - 18, .3)]:
        parts.append(f'<circle cx="{vx}" cy="{vy}" r="3.5" fill="#2dd4bf" class="via" '
                     f'style="animation-delay:{dly}s"/>')

    parts.append(f'<text x="{pad}" y="44" fill="#e2f1f8" font-size="18" font-weight="700" '
                 f'letter-spacing="2">{esc(title)}</text>')
    parts.append(f'<text x="{W - pad}" y="44" fill="#2dd4bf" font-size="12" text-anchor="end" '
                 f'opacity="0.8">{esc(note)}</text>')

    # barra base
    parts.append(f'<rect x="{barx}" y="{bary}" width="{barw}" height="{barh}" rx="13" fill="#0b2236"/>')
    # segmentos
    x = barx
    delay = 0.0
    parts.append(f'<clipPath id="barclip"><rect x="{barx}" y="{bary}" width="{barw}" '
                 f'height="{barh}" rx="13"/></clipPath>')
    parts.append('<g clip-path="url(#barclip)">')
    for r in rows:
        w = max(2, barw * r["pct"] / 100.0)
        parts.append(f'<rect x="{x:.1f}" y="{bary}" width="{w:.1f}" height="{barh}" '
                     f'fill="{r["color"]}" class="seg" style="animation-delay:{delay:.2f}s">'
                     f'<title>{esc(r["name"])} {r["pct"]:.1f}%</title></rect>')
        x += w
        delay += 0.12
    parts.append('</g>')

    # leyenda en grid
    coli = 0
    rowi = 0
    cellw = barw / legcols
    ly0 = bary + barh + 40
    for i, r in enumerate(rows):
        lx = barx + coli * cellw
        ly = ly0 + rowi * 30
        d = 0.4 + i * 0.08
        parts.append(f'<g class="lg" style="animation-delay:{d:.2f}s">')
        parts.append(f'<rect x="{lx:.1f}" y="{ly - 11}" width="12" height="12" rx="3" '
                     f'fill="{r["color"]}"/>')
        parts.append(f'<text x="{lx + 20:.1f}" y="{ly}" fill="#cfe3f0" font-size="13">'
                     f'{esc(r["name"])}</text>')
        parts.append(f'<text x="{lx + cellw - 14:.1f}" y="{ly}" fill="#7aa0b8" font-size="13" '
                     f'text-anchor="end">{r["pct"]:.1f}%</text>')
        parts.append('</g>')
        coli += 1
        if coli >= legcols:
            coli = 0
            rowi += 1
    parts.append('</svg>')
    return "".join(parts)


# --------------------------------------------------------------------------- #
#  SVG: tarjetas de metricas                                                   #
# --------------------------------------------------------------------------- #
def stats_svg(metrics):
    W, H = 1000, 132
    n = len(metrics)
    pad = 28
    gap = 16
    cw = (W - 2 * pad - gap * (n - 1)) / n
    parts = []
    parts.append(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
                 f'width="{W}" height="{H}" role="img" aria-label="Profile metrics">')
    css = """
    <style>
      .card{opacity:0;animation:up .7s ease forwards;}
      @keyframes up{from{opacity:0;transform:translateY(10px);}to{opacity:1;transform:translateY(0);}}
      .scan{animation:scan 3s linear infinite;}
      @keyframes scan{0%{opacity:0;}10%{opacity:.8;}100%{opacity:0;transform:translateX(140px);}}
      text{font-family:'Cascadia Code','Consolas',ui-monospace,monospace;}
    </style>
    """
    parts.append(css)
    parts.append(f'<rect width="{W}" height="{H}" fill="#040d18"/>')
    for i, (label, value) in enumerate(metrics):
        x = pad + i * (cw + gap)
        parts.append(f'<g class="card" style="animation-delay:{i * 0.15:.2f}s">')
        parts.append(f'<rect x="{x:.1f}" y="20" width="{cw:.1f}" height="92" rx="12" fill="#081a2c" '
                     f'stroke="#123a55" stroke-width="1.3"/>')
        parts.append(f'<rect x="{x:.1f}" y="20" width="4" height="92" rx="2" fill="#2dd4bf"/>')
        parts.append(f'<text x="{x + 22:.1f}" y="74" fill="#e2f1f8" font-size="34" '
                     f'font-weight="700">{esc(value)}</text>')
        parts.append(f'<text x="{x + 22:.1f}" y="98" fill="#6f97b0" font-size="12" '
                     f'letter-spacing="1.5">{esc(label.upper())}</text>')
        # linea de escaneo
        parts.append(f'<rect x="{x + 6:.1f}" y="22" width="2" height="88" fill="#2dd4bf" '
                     f'class="scan" style="animation-delay:{i * 0.4:.2f}s"/>')
        parts.append('</g>')
    parts.append('</svg>')
    return "".join(parts)


# --------------------------------------------------------------------------- #
#  README: seccion de proyectos                                               #
# --------------------------------------------------------------------------- #
def projects_md(repos, S):
    rows = sorted(repos, key=lambda r: r.get("updated_at", ""), reverse=True)
    th = S["th"]
    lines = [f"| {th[0]} | {th[1]} | {th[2]} | {th[3]} |", "| --- | --- | --- | --- |"]
    for r in rows:
        name = r.get("name", "")
        lang = (r.get("language") or "-")
        desc = (r.get("description") or "").strip() or "-"
        url = r.get("html_url", "")
        if r.get("private", False):
            title = "**" + esc(name) + "**"
            status = S["private"]
        else:
            title = "**[" + esc(name) + "](" + url + ")**"
            stars = r.get("stargazers_count", 0)
            status = (S["public"] + " . " + str(stars) + " " + S["stars"]) if stars else S["public"]
        lines.append(f"| {title} | `{esc(lang)}` | {esc(desc)} | {status} |")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
#  SVG: boton de idioma (pill estilo PCB)                                      #
# --------------------------------------------------------------------------- #
def button_svg(label, active):
    W, H = 150, 46
    teal = "#2dd4bf"
    if active:
        fill, txt, stroke, dot = teal, "#06202a", teal, "#06202a"
        anim = '<animate attributeName="opacity" values="1;.7;1" dur="2.4s" repeatCount="indefinite"/>'
    else:
        fill, txt, stroke, dot = "#0b2236", "#7fe9da", "#1d4f5c", teal
        anim = ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
        f'role="img" aria-label="{esc(label)}">'
        f'<rect x="2" y="2" width="{W-4}" height="{H-4}" rx="21" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="2"/>'
        f'<circle cx="28" cy="{H//2}" r="5" fill="{dot}">{anim}</circle>'
        f'<text x="{(W+18)//2}" y="{H//2+5}" fill="{txt}" text-anchor="middle" '
        f'font-family="Cascadia Code,Consolas,ui-monospace,monospace" font-size="16" '
        f'font-weight="700" letter-spacing="1">{esc(label)}</text>'
        f'</svg>')


def lang_switch(cur):
    cells = []
    for l in LANGS:
        state = "on" if l == cur else "off"
        cells.append(f'<a href="{FILES[l]}"><img src="./assets/btn-{l}-{state}.svg" '
                     f'height="38" alt="{esc(STRINGS[l]["btn"])}"/></a>')
    return '<div align="center">\n\n' + ' &nbsp; '.join(cells) + '\n\n</div>'


# --------------------------------------------------------------------------- #
#  Badges (estilo markdown-badges) + widgets auto-actualizables                #
# --------------------------------------------------------------------------- #
_BG = "0b1230"
EMAIL = "josenicole2000@gmail.com"
LINKEDIN = "https://www.linkedin.com/in/jos%C3%A9-nicolas-s%C3%A1nchez-zorrilla-76990b280/"


def _enc(s):
    return (s.replace("-", "--").replace("_", "__").replace(" ", "%20")
             .replace("+", "%2B").replace("#", "%23").replace("&", "%26"))


def badge(label, color, logo=None, logocolor="white"):
    url = f"https://img.shields.io/badge/{_enc(label)}-{color}?style=for-the-badge"
    if logo:
        url += f"&logo={logo}&logoColor={logocolor}"
    return f'<img src="{url}" alt="{esc(label)}" height="28"/>'


TECH = [
    ("Languages", "Lenguajes", [
        badge("TypeScript", "3178C6", "typescript"),
        badge("JavaScript", "F7DF1E", "javascript", "black"),
        badge("Python", "3776AB", "python"), badge("C", "A8B9CC", "c", "black"),
        badge("C++", "00599C", "cplusplus"), badge("Swift", "F05138", "swift"),
        badge("Kotlin", "7F52FF", "kotlin"), badge("Java", "ED8B00", "openjdk"),
        badge("Verilog", "848BF3"),
    ]),
    ("Web & UI", "Web y UI", [
        badge("React", "20232A", "react", "61DAFB"), badge("HTML5", "E34F26", "html5"),
        badge("CSS3", "1572B6", "css3"), badge("Node.js", "339933", "nodedotjs"),
        badge("Vite", "646CFF", "vite"),
    ]),
    ("Tooling & DevOps", "Herramientas y DevOps", [
        badge("Git", "F05032", "git"), badge("GitHub Actions", "2088FF", "githubactions"),
        badge("Docker", "2496ED", "docker"), badge("Linux", "FCC624", "linux", "black"),
        badge("VS Code", "007ACC", "visualstudiocode"),
    ]),
    ("AI & data", "IA y datos", [
        badge("OpenAI", "412991", "openai"), badge("Anthropic", "191919", "anthropic"),
        badge("Pandas", "150458", "pandas"), badge("NumPy", "013243", "numpy"),
    ]),
]


def tech_section(lang):
    blocks = []
    for en, es, items in TECH:
        label = en if lang == "en" else es
        blocks.append(f"**{esc(label)}**  \n" + " ".join(items))
    return '<div align="center">\n\n' + "\n\n".join(blocks) + "\n\n</div>"


def quick_badges():
    return (
        f'<img src="https://komarev.com/ghpvc/?username={USERNAME}&color=22d3ee&'
        f'style=for-the-badge&label=PROFILE+VIEWS" alt="views"/>\n'
        f'<img src="https://img.shields.io/github/followers/{USERNAME}?style=for-the-badge&'
        f'logo=github&color=a855f7&labelColor={_BG}" alt="followers"/>\n'
        f'<img src="https://img.shields.io/badge/Focus-developer%20tools%20%26%20AI-f472b6?'
        f'style=for-the-badge&labelColor={_BG}" alt="focus"/>')


def stats_card():
    return (f'<img height="175" src="https://github-readme-stats.vercel.app/api?'
            f'username={USERNAME}&show_icons=true&hide_border=true&count_private=true&'
            f'include_all_commits=true&bg_color={_BG}&title_color=f472b6&text_color=9fb3d8&'
            f'icon_color=22d3ee" alt="GitHub stats"/>')


def streak_card():
    return (f'<img height="175" src="https://streak-stats.demolab.com/?'
            f'user={USERNAME}&hide_border=true&background={_BG}&stroke=2dd4bf&ring=f472b6&'
            f'fire=fbbf24&currStreakLabel=22d3ee&sideLabels=9fb3d8&dates=6b7aa8&'
            f'currStreakNum=eaf2ff&sideNums=eaf2ff&dayLabels=9fb3d8" alt="streak"/>')


def activity_graph():
    return (f'<img width="100%" src="https://github-readme-activity-graph.vercel.app/graph?'
            f'username={USERNAME}&bg_color={_BG}&color=f472b6&line=22d3ee&point=fbbf24&'
            f'area=true&hide_border=true" alt="contribution activity"/>')


def trophies():
    return (f'<img src="https://github-profile-trophy.vercel.app/?username={USERNAME}&'
            f'theme=algolia&no-frame=true&no-bg=true&column=7&margin-w=6&margin-h=6" '
            f'alt="trophies"/>')


def snake_img():
    base = f"https://raw.githubusercontent.com/{USERNAME}/{USERNAME}/output"
    return f'<img width="100%" src="{base}/snake-dark.svg" alt="contribution snake"/>'


def connect_section():
    out = []
    if LINKEDIN:
        out.append(f'<a href="{LINKEDIN}"><img src="https://img.shields.io/badge/'
                   f'LinkedIn-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white" '
                   f'alt="LinkedIn"/></a>')
    out.append(f'<a href="mailto:{EMAIL}"><img src="https://img.shields.io/badge/Email-{_BG}?'
               f'style=for-the-badge&logo=gmail&logoColor=f472b6" alt="Email"/></a>')
    out.append(f'<a href="https://github.com/{USERNAME}"><img src="https://img.shields.io/badge/'
               f'GitHub-{_BG}?style=for-the-badge&logo=github&logoColor=22d3ee" alt="GitHub"/></a>')
    return "\n".join(out)


def build_readme(lang, projects_table, updated):
    S = STRINGS[lang]
    bullets = "\n".join("- " + b for b in S["bullets"])
    return f"""{lang_switch(lang)}

<div align="center">

<img src="./assets/header-{lang}.svg" width="100%" alt="{esc(FULL_NAME)}" />

{quick_badges()}

</div>

<br/>

## {S['h_stats']}

<div align="center">

{stats_card()}
&nbsp;
{streak_card()}

</div>

## {S['h_activity']}

<div align="center">

{activity_graph()}

</div>

<br/>

<div align="center">

<img src="./assets/stats-{lang}.svg" width="100%" alt="metrics" />

</div>

<br/>

<img src="./assets/languages-{lang}.svg" width="100%" alt="{esc(S['lang_title'])}" />

<br/>

## {S['h_tech']}

{tech_section(lang)}

<br/>

## {S['selected']}

{projects_table}

<br/>

## {S['h_snake']}

<div align="center">

{snake_img()}

</div>

<br/>

## {S['about_title']}

{S['about']}

{bullets}

{S['generated']}

<br/>

## {S['h_connect']}

<div align="center">

{connect_section()}

</div>

<br/>

<div align="center">

_{S['updated']}: {updated}_

</div>
"""


# --------------------------------------------------------------------------- #
#  Main                                                                        #
# --------------------------------------------------------------------------- #
def main():
    print("fetching data for", USERNAME, "...")
    repos = fetch_repos()
    profile = fetch_profile()
    langs = aggregate_languages(repos)
    top_lang = langs[0]["name"] if langs else "code"
    total_stars = sum(r.get("stargazers_count", 0) for r in repos)
    created = profile.get("created_at", "2023-01-01T00:00:00Z")[:4]
    values = [str(len(repos)), str(total_stars), str(len(langs)), created]
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    os.makedirs(ASSETS, exist_ok=True)
    # botones de idioma (contenido por idioma, estado on/off)
    for l in LANGS:
        write(os.path.join(ASSETS, f"btn-{l}-on.svg"), button_svg(STRINGS[l]["btn"], True))
        write(os.path.join(ASSETS, f"btn-{l}-off.svg"), button_svg(STRINGS[l]["btn"], False))

    for l in LANGS:
        S = STRINGS[l]
        write(os.path.join(ASSETS, f"header-{l}.svg"), header_svg(top_lang, S["roles"]))
        write(os.path.join(ASSETS, f"languages-{l}.svg"),
              languages_svg(langs, S["lang_title"], S["lang_note"]))
        metrics = list(zip(S["stats"], values))
        write(os.path.join(ASSETS, f"stats-{l}.svg"), stats_svg(metrics))
        write(os.path.join(os.path.dirname(ASSETS), FILES[l]),
              build_readme(l, projects_md(repos, S), updated))

    print("done. repos:", len(repos), "languages:", len(langs), "stars:", total_stars)


if __name__ == "__main__":
    try:
        main()
    except urllib.error.HTTPError as e:
        print("HTTP error:", e.code, e.reason, file=sys.stderr)
        sys.exit(1)
